"""
SOC Alert Triage Pipeline
Loads alerts, scores them, and outputs prioritized list with explanations.
"""

from pathlib import Path
from datetime import datetime
from data_loader import load_alerts
from scoring_engine import ScoringEngine


def print_triage_report(scored_alerts: list, risk_threshold: float = 60.0):
    """
    Print a formatted triage report.
    
    Args:
        scored_alerts: List of ScoredAlert objects
        risk_threshold: Risk score threshold for "Critical" classification
    """
    print("\n" + "="*80)
    print("SOC ALERT TRIAGE REPORT")
    print("="*80 + "\n")
    
    # Summary statistics
    critical_count = sum(1 for sa in scored_alerts if sa.priority == "Critical")
    high_count = sum(1 for sa in scored_alerts if sa.priority == "High")
    
    print(f"Total Alerts: {len(scored_alerts)}")
    print(f"Critical: {critical_count} | High: {high_count} | Medium/Low: {len(scored_alerts) - critical_count - high_count}")
    print(f"Risk Threshold: {risk_threshold}\n")
    print("-"*80 + "\n")
    
    # Detailed alert listing
    for idx, scored_alert in enumerate(scored_alerts, 1):
        alert = scored_alert.alert
        print(f"{idx}. [{scored_alert.priority.upper()}] {alert['alert_id']}")
        print(f"   Risk Score: {scored_alert.risk_score:.1f}")
        print(f"   Source: {alert['source']} | Severity: {alert['severity']} | "
              f"Asset: {alert['asset_type']} | Frequency: {alert['frequency']}")
        print(f"   Timestamp: {alert['timestamp']}")
        print(f"   Reason: {scored_alert.explanation}")
        print()
    
    print("-"*80)
    print("Report generated by AI-Assisted SOC Alert Triage")


def generate_html_report(scored_alerts: list, risk_threshold: float = 60.0, output_file: str = "alert_triage_report.html"):
    """
    Generate an HTML report and save to file.
    
    Args:
        scored_alerts: List of ScoredAlert objects
        risk_threshold: Risk score threshold for "Critical" classification
        output_file: Output HTML filename
    """
    critical_count = sum(1 for sa in scored_alerts if sa.priority == "Critical")
    high_count = sum(1 for sa in scored_alerts if sa.priority == "High")
    medium_count = sum(1 for sa in scored_alerts if sa.priority == "Medium")
    low_count = sum(1 for sa in scored_alerts if sa.priority == "Low")
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Build HTML
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SOC Alert Triage Report</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: #f5f5f5;
            color: #333;
            line-height: 1.6;
        }}
        .container {{
            max-width: 1200px;
            margin: 20px auto;
            padding: 0 20px;
        }}
        header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px 0;
            margin-bottom: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1 {{
            font-size: 28px;
            margin-bottom: 10px;
        }}
        .timestamp {{
            opacity: 0.9;
            font-size: 14px;
        }}
        .stats {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }}
        .stat-card {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid #667eea;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .stat-card.critical {{
            border-left-color: #e74c3c;
        }}
        .stat-card.high {{
            border-left-color: #f39c12;
        }}
        .stat-card.medium {{
            border-left-color: #3498db;
        }}
        .stat-card.low {{
            border-left-color: #27ae60;
        }}
        .stat-card h3 {{
            font-size: 12px;
            color: #999;
            text-transform: uppercase;
            margin-bottom: 10px;
        }}
        .stat-card .number {{
            font-size: 32px;
            font-weight: bold;
        }}
        .alerts {{
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            overflow: hidden;
        }}
        .alert-item {{
            border-bottom: 1px solid #e0e0e0;
            padding: 20px;
            transition: background-color 0.2s;
        }}
        .alert-item:last-child {{
            border-bottom: none;
        }}
        .alert-item:hover {{
            background-color: #f9f9f9;
        }}
        .alert-header {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
        }}
        .alert-id {{
            font-weight: bold;
            font-size: 16px;
            color: #333;
        }}
        .priority-badge {{
            padding: 6px 12px;
            border-radius: 4px;
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
        }}
        .priority-badge.critical {{
            background-color: #e74c3c;
            color: white;
        }}
        .priority-badge.high {{
            background-color: #f39c12;
            color: white;
        }}
        .priority-badge.medium {{
            background-color: #3498db;
            color: white;
        }}
        .priority-badge.low {{
            background-color: #27ae60;
            color: white;
        }}
        .alert-meta {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 10px;
            font-size: 14px;
            margin-bottom: 10px;
            color: #666;
        }}
        .meta-item {{
            display: flex;
            justify-content: space-between;
        }}
        .meta-label {{
            font-weight: 500;
            color: #999;
        }}
        .score-bar {{
            width: 100%;
            height: 8px;
            background-color: #e0e0e0;
            border-radius: 4px;
            overflow: hidden;
            margin-bottom: 10px;
        }}
        .score-fill {{
            height: 100%;
            background: linear-gradient(90deg, #27ae60, #f39c12, #e74c3c);
            transition: width 0.3s;
        }}
        .explanation {{
            padding: 10px;
            background-color: #f5f5f5;
            border-left: 3px solid #667eea;
            border-radius: 4px;
            font-size: 14px;
            color: #555;
        }}
        footer {{
            text-align: center;
            margin-top: 40px;
            padding: 20px;
            color: #999;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>SOC Alert Triage Report</h1>
            <p class="timestamp">Generated: {timestamp}</p>
        </header>
        
        <div class="stats">
            <div class="stat-card critical">
                <h3>Critical</h3>
                <div class="number">{critical_count}</div>
            </div>
            <div class="stat-card high">
                <h3>High</h3>
                <div class="number">{high_count}</div>
            </div>
            <div class="stat-card medium">
                <h3>Medium</h3>
                <div class="number">{medium_count}</div>
            </div>
            <div class="stat-card low">
                <h3>Low</h3>
                <div class="number">{low_count}</div>
            </div>
        </div>
        
        <div class="alerts">
            {"".join(f'''
            <div class="alert-item">
                <div class="alert-header">
                    <span class="alert-id">{sa.alert['alert_id']}</span>
                    <span class="priority-badge {sa.priority.lower()}">{sa.priority}</span>
                </div>
                <div class="score-bar">
                    <div class="score-fill" style="width: {sa.risk_score}%;"></div>
                </div>
                <div class="alert-meta">
                    <div class="meta-item">
                        <span class="meta-label">Risk Score:</span>
                        <span>{sa.risk_score:.1f}/100</span>
                    </div>
                    <div class="meta-item">
                        <span class="meta-label">Source:</span>
                        <span>{sa.alert['source']}</span>
                    </div>
                    <div class="meta-item">
                        <span class="meta-label">Severity:</span>
                        <span>{sa.alert['severity'].upper()}</span>
                    </div>
                    <div class="meta-item">
                        <span class="meta-label">Asset Type:</span>
                        <span>{sa.alert['asset_type']}</span>
                    </div>
                    <div class="meta-item">
                        <span class="meta-label">Frequency:</span>
                        <span>{sa.alert['frequency']}</span>
                    </div>
                    <div class="meta-item">
                        <span class="meta-label">Timestamp:</span>
                        <span>{sa.alert['timestamp']}</span>
                    </div>
                </div>
                <div class="explanation">{sa.explanation}</div>
            </div>
            ''' for sa in scored_alerts)}
        </div>
        
        <footer>
            <p>AI-Assisted SOC Alert Triage Prototype | Risk Threshold: {risk_threshold}</p>
        </footer>
    </div>
</body>
</html>"""
    
    # Write to file
    with open(output_file, 'w') as f:
        f.write(html_content)
    
    print(f"✓ HTML report saved to: {output_file}")


def main():
    """Run the alert triage pipeline."""
    # Configuration (configurable for tuning)
    alert_file = "mock_alerts.json"
    risk_threshold = 60.0  # Tune this value to adjust sensitivity
    
    # Optional: Custom weights for different environments
    custom_severity_weights = {
        'low': 20,
        'medium': 50,
        'high': 90
    }
    
    custom_asset_weights = {
        'standard': 10,
        'important': 50,
        'critical': 100
    }
    
    try:
        # Load alerts
        print(f"Loading alerts from {alert_file}...")
        alerts = load_alerts(alert_file)
        print(f"Loaded {len(alerts)} alerts\n")
        
        # Initialize scoring engine with configuration
        engine = ScoringEngine(
            severity_weights=custom_severity_weights,
            asset_weights=custom_asset_weights,
            frequency_factor=0.1,
            risk_threshold=risk_threshold
        )
        
        # Score and prioritize alerts
        scored_alerts = engine.score_alerts(alerts)
        
        # Print report
        print_triage_report(scored_alerts, risk_threshold)
        
        # Generate HTML report
        generate_html_report(scored_alerts, risk_threshold, "alert_triage_report.html")
        
        # Optional: Return top critical alerts
        critical_alerts = [sa for sa in scored_alerts if sa.priority == "Critical"]
        if critical_alerts:
            print(f"\n[ACTION] {len(critical_alerts)} critical alert(s) require immediate investigation.")
        
    except FileNotFoundError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"Error during triage: {e}")


if __name__ == "__main__":
    main()
